### ISSUE TITLE
Typing svg has a new url

### ISSUE THREAD

**Issue by DenverCoder1** [iamraufu/iamraufu#1]
Hi,

I'm glad you are enjoying my typing svg animation code which you have on your profile!

I have now made it into a public repository and it has a new url.

The old link will be going away, so you will need to update your link to the new url.

Link to repo: https://github.com/DenverCoder1/readme-typing-svg

Thanks :smiley: 

(PS A :star2: on the repo would be nice :wink:)

**Comment by iamraufu** [comment]
Hello Denver,

Hope you are doing well in this pandemic situation. 

Your typing SVG is really good. I am using this on my profile and it is currently visible. I will add the new URL as soon as you update. Thanks for your letting me know.
